In [16]:
import pandas as pd
import numpy as np
from sklearn.model_selection import train_test_split
import matplotlib.pyplot as plt
from sklearn.linear_model import LinearRegression

In [17]:
data=pd.read_csv("DataSets-master/500_Person_Gender_Height_Weight_Index.csv")

In [18]:
data.head()

Gender  Height  Weight  Index
0    Male     174      96      4
1    Male     189      87      2
2  Female     185     110      4
3  Female     195     104      3
4    Male     149      61      3

NameError: name 'data' is not defined

In [19]:
#male=0 female=1
gender = {'Male': 0,'Female': 1} 
data.Gender = [gender[item] for item in data.Gender] 
data.head()

Gender  Height  Weight  Index
0       0     174      96      4
1       0     189      87      2
2       1     185     110      4
3       1     195     104      3
4       0     149      61      3

In [20]:
data.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 500 entries, 0 to 499
Data columns (total 4 columns):
Gender    500 non-null int64
Height    500 non-null int64
Weight    500 non-null int64
Index     500 non-null int64
dtypes: int64(4)
memory usage: 15.7 KB


In [21]:
inp=data.iloc[:,0:3].values
out=data.iloc[:,3].values

In [22]:
train_x,test_x,train_y,test_y=train_test_split(inp,out,test_size=0.3,random_state=0)

In [23]:
cf=LinearRegression()
cf.fit(train_x,train_y)

LinearRegression(copy_X=True, fit_intercept=True, n_jobs=1, normalize=False)

In [24]:
pred_op=cf.predict(test_x)

In [27]:
test_x

array([[  1, 178, 154],
       [  0, 183, 147],
       [  0, 166, 107],
       [  0, 159, 140],
       [  0, 152, 132],
       [  1, 153, 107],
       [  0, 188,  99],
       [  1, 179, 150],
       [  0, 181, 105],
       [  1, 168, 140],
       [  0, 166,  61],
       [  0, 153,  70],
       [  1, 167,  58],
       [  0, 149, 100],
       [  0, 174, 138],
       [  1, 185, 102],
       [  0, 161, 115],
       [  0, 174,  90],
       [  1, 155, 111],
       [  0, 144,  80],
       [  1, 150,  87],
       [  1, 185,  94],
       [  0, 178,  85],
       [  1, 181, 106],
       [  0, 185,  76],
       [  0, 188,  65],
       [  1, 153, 149],
       [  1, 186, 127],
       [  0, 142,  69],
       [  1, 177,  81],
       [  1, 153,  77],
       [  0, 144, 108],
       [  1, 158, 149],
       [  0, 154, 100],
       [  0, 174,  95],
       [  1, 198,  50],
       [  1, 180, 156],
       [  1, 172,  90],
       [  0, 184, 153],
       [  1, 174,  65],
       [  0, 153, 104],
       [  1, 188

In [28]:
test_y

array([5, 5, 4, 5, 5, 5, 3, 5, 4, 5, 2, 3, 2, 5, 5, 3, 5, 3, 5, 4, 4, 3,
       3, 4, 2, 1, 5, 4, 4, 3, 4, 5, 5, 5, 4, 0, 5, 4, 5, 2, 5, 4, 4, 5,
       4, 2, 5, 2, 5, 5, 4, 4, 3, 5, 5, 3, 4, 4, 0, 4, 4, 4, 4, 1, 4, 4,
       2, 3, 5, 4, 5, 5, 3, 4, 4, 5, 4, 4, 5, 5, 5, 3, 4, 5, 5, 2, 5, 5,
       5, 4, 2, 2, 3, 1, 3, 1, 4, 4, 0, 3, 5, 5, 4, 3, 5, 5, 2, 5, 4, 4,
       4, 5, 3, 3, 5, 5, 5, 4, 4, 5, 2, 5, 5, 5, 5, 5, 5, 2, 2, 4, 4, 5,
       4, 3, 4, 2, 4, 2, 0, 5, 5, 5, 3, 3, 4, 3, 4, 4, 5, 3])

In [30]:
test_x[1]

array([  0, 183, 147])

In [31]:
test_y[1]

5

In [32]:
pred_op[1]

4.678212929677489